apiVersion: v1
kind: Service
metadata:
  name: pruebagcp-app-service
  namespace: pruebas
spec:
  type: LoadBalancer
  selector:
    app: pruebagcp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
